name: toys-ecommerce

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: toys-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    restart: unless-stopped